version: '2.4'
services:
  nginx:
    image: nginx
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./volumes/static:/usr/share/nginx/static
    restart: always
    networks:
      - proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.basic.frontend.rule=Host:featureprocessor.harpy.dev
      - traefik.basic.port=80
      - com.centurylinklabs.watchtower.enable=true

  # PostgreSQL database for Django
  db:
    image: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=StrongPassword
      - POSTGRES_DB=postgres
    restart: always
    labels:
      - traefik.enable=false
    ports:
      - "5433:5432"

networks:
  proxy:
    external: true
