# Generated by Django 2.2.7 on 2019-11-05 11:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_functions', models.IntegerField(default=-1)),
                ('number_of_quantifiers', models.IntegerField(default=-1)),
                ('number_of_variables', models.IntegerField(default=-1)),
                ('number_of_arrays', models.IntegerField(default=-1)),
                ('dagsize', models.IntegerField(default=-1)),
                ('treesize', models.IntegerField(default=-1)),
                ('dependency_score', models.FloatField(default=-1)),
                ('variable_equivalence_class_sizes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), size=None)),
                ('biggest_equivalence_class', models.IntegerField(default=-1)),
                ('occuring_sorts', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None), size=None)),
                ('occuring_functions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('occuring_quantifiers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('contains_arrays', models.BooleanField(default=False)),
                ('assertion_stack', models.CharField(max_length=256)),
                ('assertion_stack_hashcode', models.BigIntegerField(default=-1)),
                ('solver_result', models.CharField(max_length=20)),
                ('solver_time', models.FloatField(default=-1)),
            ],
        ),
    ]
