# Generated by Django 2.2.7 on 2019-11-13 13:01

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_functions', models.IntegerField(default=-1, null=True)),
                ('number_of_quantifiers', models.IntegerField(default=-1, null=True)),
                ('number_of_variables', models.IntegerField(default=-1, null=True)),
                ('number_of_arrays', models.IntegerField(default=-1, null=True)),
                ('dagsize', models.IntegerField(default=-1, null=True)),
                ('treesize', models.IntegerField(default=-1, null=True)),
                ('dependency_score', models.FloatField(default=-1, null=True)),
                ('variable_equivalence_class_sizes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), blank=True, null=True, size=None)),
                ('biggest_equivalence_class', models.IntegerField(default=-1, null=True)),
                ('occuring_sorts', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('occuring_functions', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('occuring_quantifiers', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('contains_arrays', models.BooleanField(db_index=True, default=False, null=True)),
                ('assertion_stack', models.TextField(default='', null=True)),
                ('assertion_stack_hashcode', models.BigIntegerField(db_index=True, default=-1, null=True)),
                ('solver_result', models.CharField(db_index=True, max_length=20, null=True)),
                ('solver_time', models.FloatField(default=-1, null=True)),
                ('solver_name', models.CharField(db_index=True, max_length=128, null=True)),
            ],
        ),
    ]
