# Generated by Django 2.2.7 on 2019-11-05 11:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtfeature',
            name='occuring_functions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='occuring_quantifiers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='occuring_sorts',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='variable_equivalence_class_sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), blank=True, null=True, size=None),
        ),
    ]
