# Generated by Django 2.2.7 on 2019-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0002_auto_20191105_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtfeature',
            name='assertion_stack',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='assertion_stack_hashcode',
            field=models.BigIntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='biggest_equivalence_class',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='contains_arrays',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='dagsize',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='dependency_score',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='number_of_arrays',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='number_of_functions',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='number_of_quantifiers',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='number_of_variables',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='solver_result',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='solver_time',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='smtfeature',
            name='treesize',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
