# Generated by Django 2.2.7 on 2019-11-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0003_auto_20191105_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtfeature',
            name='assertion_stack',
            field=models.TextField(default=None, null=True),
        ),
    ]
