# Generated by Django 2.2.7 on 2019-11-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0004_auto_20191106_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtfeature',
            name='assertion_stack_hashcode',
            field=models.BigIntegerField(db_index=True, default=-1, null=True),
        ),
    ]
